//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StkStubaki.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mec()
        {
            this.SetMecs = new HashSet<SetMec>();
        }
    
        public int IdMec { get; set; }
        public int RedniBrMec { get; set; }
        public int IdUtakmica { get; set; }
        public Nullable<int> IdDomaciIgrac { get; set; }
        public Nullable<int> IdGostujuciIgrac { get; set; }
        public Nullable<int> DobSetoviDom { get; set; }
        public Nullable<int> DobSetoviGost { get; set; }
    
        public virtual Igrac Igrac { get; set; }
        public virtual Igrac Igrac1 { get; set; }
        public virtual Utakmica Utakmica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetMec> SetMecs { get; set; }
    }
}
