//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StkStubaki.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Natjece
    {
        public int SifraSezona { get; set; }
        public int IdMomcad { get; set; }
        public Nullable<int> BrUtakmica { get; set; }
        public Nullable<int> BrPobjeda { get; set; }
        public Nullable<int> BrPoraza { get; set; }
        public Nullable<int> BrNerijesenih { get; set; }
        public Nullable<int> DobiveniMecevi { get; set; }
        public Nullable<int> IzgubljeniMecevi { get; set; }
        public Nullable<int> BrBodova { get; set; }
        public Nullable<int> Kazna { get; set; }
        public string OpisKazne { get; set; }
    
        public virtual Momcad Momcad { get; set; }
    }
}
