//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StkStubaki.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Par
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Par()
        {
            this.SetPars = new HashSet<SetPar>();
        }
    
        public int IdPar { get; set; }
        public int IdUtakmica { get; set; }
        public int IdDomacin1 { get; set; }
        public int IdDomacin2 { get; set; }
        public int IdGost1 { get; set; }
        public int IdGost2 { get; set; }
        public int SetoviDomacin { get; set; }
        public int SetoviGost { get; set; }
    
        public virtual Igrac Igrac { get; set; }
        public virtual Igrac Igrac1 { get; set; }
        public virtual Igrac Igrac2 { get; set; }
        public virtual Igrac Igrac3 { get; set; }
        public virtual Utakmica Utakmica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetPar> SetPars { get; set; }
    }
}
