//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StkStubaki.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetPar
    {
        public int RedniBroj { get; set; }
        public int RezD { get; set; }
        public int RezG { get; set; }
        public int IdSetPar { get; set; }
        public int IdPar { get; set; }
    
        public virtual Par Par { get; set; }
    }
}
