//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StkStubaki.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utakmica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utakmica()
        {
            this.Mecs = new HashSet<Mec>();
            this.Pars = new HashSet<Par>();
        }
    
        public int IdUtakmica { get; set; }
        public int SifraSezona { get; set; }
        public int IdDomacin { get; set; }
        public int IdGost { get; set; }
        public int Kolo { get; set; }
        public Nullable<int> RezDomacin { get; set; }
        public Nullable<int> RezGost { get; set; }
        public Nullable<int> BrSetDomacin { get; set; }
        public Nullable<int> BrSetGost { get; set; }
        public string Liga { get; set; }
        public Nullable<int> Zakljucano { get; set; }
        public Nullable<int> Korisnik { get; set; }
        public string Akcija { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mec> Mecs { get; set; }
        public virtual Momcad Momcad { get; set; }
        public virtual Momcad Momcad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Par> Pars { get; set; }
        public virtual Sezona Sezona { get; set; }
    }
}
